# The contacts button on WeChat app
contacts:
    x: 289
    "y": 193
    margin_x: 10
    margin_y: 10
# The more button on WeChat app
more:
    x: 293
    "y": 946
    margin_x: 100
    margin_y: 10
# The messages buttons bar on WeChat app
messages_bar:
    x: 605
    "y": 782
    margin_x: 100
    margin_y: 100
# The right click on contact, popup menu on WeChat app
messages_popup:
    x: 0
    "y": 0
    margin_x: 20
    margin_y: -10

# Application title to activate
app_title: WeChat
# Max count of messages to send
max_count: 3
# Interval between messages sent (ms)
interval: 100
# Whether to check the last contact is the end of contacts list
check_end: true
# Whether to send message automatically
auto_send: true
# Whether debug or not
debug: false