// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package i18n

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en": &dictionary{index: enIndex, data: enData},
		"zh": &dictionary{index: zhIndex, data: zhData},
	}
	fallback := language.MustParse("en")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"  clear - Clear messages that input but not sent\n":        4,
	"  proc  - Run automation process based on settings.yml\n":  3,
	"  scan  - Scan for UI elements and save to settings.yml\n": 2,
	"--- Please press ctrl + shift + q to stop ---\n":           18,
	"Active App: %s\n":                       17,
	"Automation sequence completed.\n":       26,
	"Contact did not change (End of list)\n": 27,
	"Images directory not found at: %s. Please make sure the 'imgs' folder is present.\n": 21,
	"Last contact not found: [match:%0.3f]\n":                                             32,
	"Last contact pos: %v [match:%0.3f]\n":                                                31,
	"Left Click: %s\n":                                                                    6,
	"Loaded settings: %+v\n":                                                              20,
	"Move relative (%d, %d): %s\n":                                                        16,
	"Move to (%d, %d): %s\n":                                                              15,
	"Paste Clipboard: %s\n":                                                               14,
	"Please open WeChat app first.\n":                                                     23,
	"Press Ctrl+A: %s\n":                                                                  10,
	"Press Delete: %s\n":                                                                  11,
	"Press Down: %s\n":                                                                    13,
	"Press Enter: %s\n":                                                                   9,
	"Press Esc: %s\n":                                                                     8,
	"Press Up: %s\n":                                                                      12,
	"Reach the end of contact list.\n":                                                    25,
	"Right Click: %s\n":                                                                   7,
	"Starting automation sequence...\n":                                                   24,
	"Stopped.\n":                                                                          19,
	"Subcommands:\n":                                                                      1,
	"Unknown subcommand: %s\n":                                                            5,
	"Usage: auto-wechat <subcommand>\n":                                                   0,
	"active app error: %v\n":                                                              22,
	"captureAppImage[%d, %d, %d, %d]: capture failed: %v\n":                               29,
	"captureContact: capture failed: %v\n":                                                30,
	"get app window bounds error: %v\n":                                                   28,
}

var enIndex = []uint32{ // 34 elements
	// Entry 0 - 1F
	0x00000000, 0x00000025, 0x00000037, 0x00000074,
	0x000000b0, 0x000000e6, 0x00000105, 0x0000011c,
	0x00000134, 0x0000014a, 0x00000162, 0x0000017b,
	0x00000194, 0x000001a9, 0x000001c0, 0x000001dc,
	0x000001ff, 0x00000228, 0x0000023f, 0x00000272,
	0x00000280, 0x0000029d, 0x000002f7, 0x00000314,
	0x00000337, 0x0000035c, 0x00000380, 0x000003a4,
	0x000003ce, 0x000003f6, 0x0000043e, 0x00000469,
	// Entry 20 - 3F
	0x00000497, 0x000004c5,
} // Size: 160 bytes

const enData string = "" + // Size: 1221 bytes
	"\x04\x00\x01\x0a \x02Usage: auto-wechat <subcommand>\x04\x00\x01\x0a\x0d" +
	"\x02Subcommands:\x04\x02  \x01\x0a6\x02scan  - Scan for UI elements and " +
	"save to settings.yml\x04\x02  \x01\x0a5\x02proc  - Run automation proces" +
	"s based on settings.yml\x04\x02  \x01\x0a/\x02clear - Clear messages tha" +
	"t input but not sent\x04\x00\x01\x0a\x1a\x02Unknown subcommand: %[1]s" +
	"\x04\x00\x01\x0a\x12\x02Left Click: %[1]s\x04\x00\x01\x0a\x13\x02Right C" +
	"lick: %[1]s\x04\x00\x01\x0a\x11\x02Press Esc: %[1]s\x04\x00\x01\x0a\x13" +
	"\x02Press Enter: %[1]s\x04\x00\x01\x0a\x14\x02Press Ctrl+A: %[1]s\x04" +
	"\x00\x01\x0a\x14\x02Press Delete: %[1]s\x04\x00\x01\x0a\x10\x02Press Up:" +
	" %[1]s\x04\x00\x01\x0a\x12\x02Press Down: %[1]s\x04\x00\x01\x0a\x17\x02P" +
	"aste Clipboard: %[1]s\x04\x00\x01\x0a\x1e\x02Move to (%[1]d, %[2]d): %[3" +
	"]s\x04\x00\x01\x0a$\x02Move relative (%[1]d, %[2]d): %[3]s\x04\x00\x01" +
	"\x0a\x12\x02Active App: %[1]s\x04\x00\x01\x0a.\x02--- Please press ctrl " +
	"+ shift + q to stop ---\x04\x00\x01\x0a\x09\x02Stopped.\x04\x00\x01\x0a" +
	"\x18\x02Loaded settings: %+[1]v\x04\x00\x01\x0aU\x02Images directory not" +
	" found at: %[1]s. Please make sure the 'imgs' folder is present.\x04\x00" +
	"\x01\x0a\x18\x02active app error: %[1]v\x04\x00\x01\x0a\x1e\x02Please op" +
	"en WeChat app first.\x04\x00\x01\x0a \x02Starting automation sequence..." +
	"\x04\x00\x01\x0a\x1f\x02Reach the end of contact list.\x04\x00\x01\x0a" +
	"\x1f\x02Automation sequence completed.\x04\x00\x01\x0a%\x02Contact did n" +
	"ot change (End of list)\x04\x00\x01\x0a#\x02get app window bounds error:" +
	" %[1]v\x04\x00\x01\x0aC\x02captureAppImage[%[1]d, %[2]d, %[3]d, %[4]d]: " +
	"capture failed: %[5]v\x04\x00\x01\x0a&\x02captureContact: capture failed" +
	": %[1]v\x04\x00\x01\x0a)\x02Last contact pos: %[1]v [match:%0.3[2]f]\x04" +
	"\x00\x01\x0a)\x02Last contact not found: [match:%0.3[1]f]"

var zhIndex = []uint32{ // 34 elements
	// Entry 0 - 1F
	0x00000000, 0x00000025, 0x00000035, 0x0000006e,
	0x000000a7, 0x000000db, 0x000000f7, 0x00000110,
	0x00000129, 0x00000140, 0x00000159, 0x00000173,
	0x0000018d, 0x000001a3, 0x000001bb, 0x000001d7,
	0x000001fc, 0x00000224, 0x0000023d, 0x00000269,
	0x0000027b, 0x00000298, 0x000002e3, 0x00000302,
	0x00000323, 0x00000341, 0x00000365, 0x00000386,
	0x000003ad, 0x000003d8, 0x0000041e, 0x00000447,
	// Entry 20 - 3F
	0x0000047e, 0x000004b2,
} // Size: 160 bytes

const zhData string = "" + // Size: 1202 bytes
	"\x04\x00\x01\x0a \x02用法: auto-wechat <子命令>\x04\x00\x01\x0a\x0b\x02子命令:" +
	"\x04\x02  \x01\x0a2\x02scan  - 扫描 UI 元素并保存到 settings.yml\x04\x02  \x01" +
	"\x0a2\x02proc  - 基于 settings.yml 运行自动化流程\x04\x02  \x01\x0a-\x02clear - 清" +
	"除已输入但未发送的消息\x04\x00\x01\x0a\x17\x02未知子命令: %[1]s\x04\x00\x01\x0a\x14" +
	"\x02左键点击: %[1]s\x04\x00\x01\x0a\x14\x02右键点击: %[1]s\x04\x00\x01\x0a\x12" +
	"\x02按下 Esc: %[1]s\x04\x00\x01\x0a\x14\x02按下 Enter: %[1]s\x04\x00\x01\x0a" +
	"\x15\x02按下 Ctrl+A: %[1]s\x04\x00\x01\x0a\x15\x02按下 Delete: %[1]s\x04\x00" +
	"\x01\x0a\x11\x02按下 Up: %[1]s\x04\x00\x01\x0a\x13\x02按下 Down: %[1]s\x04" +
	"\x00\x01\x0a\x17\x02粘贴剪贴板: %[1]s\x04\x00\x01\x0a \x02移动到 (%[1]d, %[2]d):" +
	" %[3]s\x04\x00\x01\x0a#\x02相对移动 (%[1]d, %[2]d): %[3]s\x04\x00\x01\x0a" +
	"\x14\x02激活应用: %[1]s\x04\x00\x01\x0a'\x02--- 请按 ctrl + shift + q 停止 ---" +
	"\x04\x00\x01\x0a\x0d\x02已停止。\x04\x00\x01\x0a\x18\x02已加载设置: %+[1]v\x04" +
	"\x00\x01\x0aF\x02在 %[1]s 未找到图片目录。请确保 'imgs' 文件夹存在。\x04\x00\x01\x0a\x1a" +
	"\x02激活应用错误: %[1]v\x04\x00\x01\x0a\x1c\x02请先打开微信应用。\x04\x00\x01\x0a\x19" +
	"\x02开始自动化流程...\x04\x00\x01\x0a\x1f\x02到达联系人列表末尾。\x04\x00\x01\x0a\x1c\x02" +
	"自动化流程已完成。\x04\x00\x01\x0a\x22\x02联系人未变化 (列表末尾)\x04\x00\x01\x0a&\x02获取应" +
	"用窗口边界错误: %[1]v\x04\x00\x01\x0aA\x02captureAppImage[%[1]d, %[2]d, %[3]d" +
	", %[4]d]: 截图失败: %[5]v\x04\x00\x01\x0a$\x02captureContact: 截图失败: %[1]v" +
	"\x04\x00\x01\x0a2\x02最后联系人位置: %[1]v [匹配度:%0.3[2]f]\x04\x00\x01\x0a/\x02未" +
	"找到最后联系人: [匹配度:%0.3[1]f]"

	// Total table size 2743 bytes (2KiB); checksum: 38C22374
